### ISSUE TITLE
Sidekiq::Extensions::DelayedMailer#default (NoMethodError) "undefined method `request_was_rejected' for RequestMailer:Class"

### ISSUE THREAD

**Issue by uriklar** [uriklar/ZikaronBasalon#126]
<table><tr><th>Exception</th><td>undefined method `request_was_rejected&#39; for RequestMailer:Class</td></tr><tr><th>Last Occurrence</th><td>April 19, 2016 05:40:24 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/actionmailer-3.2.14/lib/action_mailer/base.rb:438:in `method_missing'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/extensions/action_mailer.rb:17:in `public_send'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/extensions/action_mailer.rb:17:in `perform'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:150:in `execute_job'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/e42515cbbc4ac90fc7b99bc5a91704b42b7ac203/config/initializers/party_foul_sidekiq.rb#L5'>[app].../config/initializers/party_foul_sidekiq.rb:5:in `call'</a>
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/logging.rb:30:in `with_context'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:132:in `call'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:132:in `invoke'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:127:in `block in process'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:166:in `stats'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:126:in `process'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:79:in `process_one'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:67:in `run'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/util.rb:16:in `watchdog'
[bundle].../gems/sidekiq-4.1.0/lib/sidekiq/util.rb:24:in `block in safe_thread'</pre>
Fingerprint: `529d2a9b542471146fd0cc3e85190a0188aaebdb`

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 19, 2016 05:40:24 +0000</td></tr><tr><th>Params</th><td><table><tr><th>class</th><td>Sidekiq::Extensions::DelayedMailer</td></tr><tr><th>args</th><td>[&quot;---\n- !ruby/class &#39;RequestMailer&#39;\n- :request_was_rejected\n- - 154\n  - 2121\n&quot;]</td></tr><tr><th>retry</th><td>true</td></tr><tr><th>queue</th><td>default</td></tr><tr><th>jid</th><td>fa33b8f553a854d2fa6becb8</td></tr><tr><th>enqueued_at</th><td>1436245418.4676228</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 19, 2016 05:40:51 +0000</td></tr><tr><th>Params</th><td><table><tr><th>class</th><td>Sidekiq::Extensions::DelayedMailer</td></tr><tr><th>args</th><td>[&quot;---\n- !ruby/class &#39;RequestMailer&#39;\n- :request_was_rejected\n- - 154\n  - 2121\n&quot;]</td></tr><tr><th>retry</th><td>true</td></tr><tr><th>queue</th><td>default</td></tr><tr><th>jid</th><td>fa33b8f553a854d2fa6becb8</td></tr><tr><th>enqueued_at</th><td>1461044451.9217682</td></tr><tr><th>error_message</th><td>undefined method `request_was_rejected&#39; for RequestMailer:Class</td></tr><tr><th>error_class</th><td>NoMethodError</td></tr><tr><th>failed_at</th><td>1461044424.5696054</td></tr><tr><th>retry_count</th><td>0</td></tr><tr><th>created_at</th><td>1461044451.9217167</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 19, 2016 05:42:08 +0000</td></tr><tr><th>Params</th><td><table><tr><th>class</th><td>Sidekiq::Extensions::DelayedMailer</td></tr><tr><th>args</th><td>[&quot;---\n- !ruby/class &#39;RequestMailer&#39;\n- :request_was_rejected\n- - 154\n  - 2121\n&quot;]</td></tr><tr><th>retry</th><td>true</td></tr><tr><th>queue</th><td>default</td></tr><tr><th>jid</th><td>fa33b8f553a854d2fa6becb8</td></tr><tr><th>enqueued_at</th><td>1461044528.607353</td></tr><tr><th>error_message</th><td>undefined method `request_was_rejected&#39; for RequestMailer:Class</td></tr><tr><th>error_class</th><td>NoMethodError</td></tr><tr><th>failed_at</th><td>1461044424.5696054</td></tr><tr><th>retry_count</th><td>1</td></tr><tr><th>created_at</th><td>1461044451.9217167</td></tr><tr><th>retried_at</th><td>1461044452.3808582</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 19, 2016 05:44:06 +0000</td></tr><tr><th>Params</th><td><table><tr><th>class</th><td>Sidekiq::Extensions::DelayedMailer</td></tr><tr><th>args</th><td>[&quot;---\n- !ruby/class &#39;RequestMailer&#39;\n- :request_was_rejected\n- - 154\n  - 2121\n&quot;]</td></tr><tr><th>retry</th><td>true</td></tr><tr><th>queue</th><td>default</td></tr><tr><th>jid</th><td>fa33b8f553a854d2fa6becb8</td></tr><tr><th>enqueued_at</th><td>1461044646.3514383</td></tr><tr><th>error_message</th><td>undefined method `request_was_rejected&#39; for RequestMailer:Class</td></tr><tr><th>error_class</th><td>NoMethodError</td></tr><tr><th>failed_at</th><td>1461044424.5696054</td></tr><tr><th>retry_count</th><td>2</td></tr><tr><th>created_at</th><td>1461044451.9217167</td></tr><tr><th>retried_at</th><td>1461044529.0589743</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 19, 2016 05:47:09 +0000</td></tr><tr><th>Params</th><td><table><tr><th>class</th><td>Sidekiq::Extensions::DelayedMailer</td></tr><tr><th>args</th><td>[&quot;---\n- !ruby/class &#39;RequestMailer&#39;\n- :request_was_rejected\n- - 154\n  - 2121\n&quot;]</td></tr><tr><th>retry</th><td>true</td></tr><tr><th>queue</th><td>default</td></tr><tr><th>jid</th><td>fa33b8f553a854d2fa6becb8</td></tr><tr><th>enqueued_at</th><td>1461044829.6046188</td></tr><tr><th>error_message</th><td>undefined method `request_was_rejected&#39; for RequestMailer:Class</td></tr><tr><th>error_class</th><td>NoMethodError</td></tr><tr><th>failed_at</th><td>1461044424.5696054</td></tr><tr><th>retry_count</th><td>3</td></tr><tr><th>created_at</th><td>1461044451.9217167</td></tr><tr><th>retried_at</th><td>1461044646.7490277</td></tr></table></td></tr></table>
