### ISSUE TITLE
RegistrationsController#create (ActiveRecord::RecordNotUnique) "PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_email"
DETAIL:  Key (email)=(galitbecker@gmail.com) already exists.
: INSERT INTO "users" ("admin", "created_at", "current_sign_in_at", "current_sign_in_ip", "email", "encrypted_password", "full_name", "last_sign_in_at", "last_sign_in_ip", "meta_id", "meta_type", "phone", "remember_created_at", "reset_password_sent_at", "reset_password_token", "sign_in_count", "sub_admin", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) RETURNING "id""

### ISSUE THREAD

**Issue by uriklar** [uriklar/ZikaronBasalon#129]
<table><tr><th>Exception</th><td>PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint &quot;index_users_on_email&quot;
DETAIL:  Key (email)=(galitbecker@gmail.com) already exists.
: INSERT INTO &quot;users&quot; (&quot;admin&quot;, &quot;created_at&quot;, &quot;current_sign_in_at&quot;, &quot;current_sign_in_ip&quot;, &quot;email&quot;, &quot;encrypted_password&quot;, &quot;full_name&quot;, &quot;last_sign_in_at&quot;, &quot;last_sign_in_ip&quot;, &quot;meta_id&quot;, &quot;meta_type&quot;, &quot;phone&quot;, &quot;remember_created_at&quot;, &quot;reset_password_sent_at&quot;, &quot;reset_password_token&quot;, &quot;sign_in_count&quot;, &quot;sub_admin&quot;, &quot;updated_at&quot;) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) RETURNING &quot;id&quot;</td></tr><tr><th>Last Occurrence</th><td>April 21, 2016 07:32:36 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `get_last_result'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `exec_cache'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `block in exec_query'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/active_record.rb:59:in `block in log_with_newrelic_instrumentation'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/active_record.rb:56:in `log_with_newrelic_instrumentation'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `exec_query'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/database_statements.rb:63:in `exec_insert'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/database_statements.rb:90:in `insert'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
[bundle].../gems/activerecord-3.2.14/lib/active_record/relation.rb:66:in `insert'
[bundle].../gems/activerecord-3.2.14/lib/active_record/persistence.rb:367:in `create'
[bundle].../gems/activerecord-3.2.14/lib/active_record/timestamp.rb:58:in `create'
[bundle].../gems/activerecord-3.2.14/lib/active_record/callbacks.rb:268:in `block in create'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:403:in `_run__455323123943586593__create__2521343089093350510__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/activerecord-3.2.14/lib/active_record/callbacks.rb:268:in `create'
[bundle].../gems/activerecord-3.2.14/lib/active_record/persistence.rb:348:in `create_or_update'
[bundle].../gems/activerecord-3.2.14/lib/active_record/callbacks.rb:264:in `block in create_or_update'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:414:in `_run__455323123943586593__save__2521343089093350510__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/activerecord-3.2.14/lib/active_record/callbacks.rb:264:in `create_or_update'
[bundle].../gems/activerecord-3.2.14/lib/active_record/persistence.rb:84:in `save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/validations.rb:50:in `save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/attribute_methods/dirty.rb:22:in `save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:259:in `block (2 levels) in save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:208:in `transaction'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:259:in `block in save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:258:in `save'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/active_record_helper.rb:26:in `block in save'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/transaction.rb:848:in `with_database_metric_name'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent.rb:572:in `with_database_metric_name'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/active_record_helper.rb:25:in `save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/autosave_association.rb:392:in `save_has_one_association'
[bundle].../gems/activerecord-3.2.14/lib/active_record/autosave_association.rb:197:in `block in add_autosave_association_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `_run__4241567567204222373__create__2521343089093350510__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/activerecord-3.2.14/lib/active_record/callbacks.rb:268:in `create'
[bundle].../gems/activerecord-3.2.14/lib/active_record/persistence.rb:348:in `create_or_update'
[bundle].../gems/activerecord-3.2.14/lib/active_record/callbacks.rb:264:in `block in create_or_update'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:414:in `_run__4241567567204222373__save__2521343089093350510__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/activerecord-3.2.14/lib/active_record/callbacks.rb:264:in `create_or_update'
[bundle].../gems/activerecord-3.2.14/lib/active_record/persistence.rb:84:in `save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/validations.rb:50:in `save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/attribute_methods/dirty.rb:22:in `save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:259:in `block (2 levels) in save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:208:in `transaction'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:259:in `block in save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:258:in `save'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/active_record_helper.rb:26:in `block in save'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/transaction.rb:848:in `with_database_metric_name'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent.rb:572:in `with_database_metric_name'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/active_record_helper.rb:25:in `save'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/537987dceff0b6a58d717b036add26d64062ee8a/app/controllers/registrations_controller.rb#L17'>[app].../app/controllers/registrations_controller.rb:17:in `create'</a>
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:167:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:447:in `_run__1188046070181785160__process_action__867742156193806946__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:17:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
[bundle].../gems/activerecord-3.2.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:30:in `block in process_action'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:25:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:121:in `process'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:45:in `process'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:203:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:246:in `block in action'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:36:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/mapper.rb:43:in `call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:608:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/etag.rb:23:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/conditionalget.rb:35:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/head.rb:14:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/flash.rb:242:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
[bundle].../gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/cookies.rb:341:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/query_cache.rb:64:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `_run__3315423195336015180__call__2521343089093350510__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:32:in `call_app'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/tagged_logging.rb:22:in `tagged'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/request_id.rb:22:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/static.rb:63:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:140:in `forward'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:147:in `pass'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:159:in `invalidate'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:74:in `call!'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:51:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/engine.rb:484:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/application.rb:231:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/railtie/configurable.rb:30:in `method_missing'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/content_length.rb:14:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/log_tailer.rb:17:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/handler/webrick.rb:59:in `service'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/537987dceff0b6a58d717b036add26d64062ee8a/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L138'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/537987dceff0b6a58d717b036add26d64062ee8a/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L94'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/537987dceff0b6a58d717b036add26d64062ee8a/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb#L295'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'</a></pre>
Fingerprint: `49daf43aceb91b353a18e4e823faeff93d39168c`

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 21, 2016 07:32:36 +0000</td></tr><tr><th>URL</th><td>[POST] http://zikaronbasalon.herokuapp.com/users.json</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td><table><tr><th>email</th><td>galitbecker@gmail.com</td></tr><tr><th>password</th><td>[FILTERED]</td></tr><tr><th>password_confirmation</th><td>[FILTERED]</td></tr><tr><th>full_name</th><td>גלית בקר שומן</td></tr><tr><th>type</th><td>guest</td></tr></table></td></tr><tr><th>phone</th><td>0584488622</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>registrations</td></tr><tr><th>format</th><td>json</td></tr><tr><th>registration</th><td><table><tr><th>user</th><td><table><tr><th>email</th><td>galitbecker@gmail.com</td></tr><tr><th>password</th><td>[FILTERED]</td></tr><tr><th>password_confirmation</th><td>[FILTERED]</td></tr><tr><th>full_name</th><td>גלית בקר שומן</td></tr><tr><th>type</th><td>guest</td></tr></table></td></tr><tr><th>phone</th><td>0584488622</td></tr></table></td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>e36577a6e4c3fb716a5f0c5fc6ab6eb0</td></tr><tr><th>_csrf_token</th><td>uHcmSgDdtnv9XEYQhmiKHqNx5b0eVicENV2Gkd8yu2A=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/37.26.146.151&#39;&gt;37.26.146.151&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (iPhone; CPU iPhone OS 9_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13C75 [FBAN/FBIOS;FBAV/52.0.0.46.157;FBBV/26424168;FBDV/iPhone7,2;FBMD/iPhone;FBSN/iPhone OS;FBSV/9.2;FBSS/2; FBCR/Carrier;FBID/phone;FBLC/en_US;FBOP/5]</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>application/json, text/plain, */*</td></tr></table></td></tr></table>
