### ISSUE TITLE
WitnessesController#unassign (NoMethodError) "undefined method `update_column' for nil:NilClass"

### ISSUE THREAD

**Issue by uriklar** [uriklar/ZikaronBasalon#137]
<table><tr><th>Exception</th><td>undefined method `update_column&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>May 01, 2016 08:46:28 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/uriklar/ZikaronBasalon/blob/bee90aae008434c67bc5dae3567be852152fe9da/app/controllers/witnesses_controller.rb#L121'>[app].../app/controllers/witnesses_controller.rb:121:in `unassign'</a>
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:167:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:436:in `_run__3538583488502840894__process_action__3044256208554154358__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:17:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
[bundle].../gems/activerecord-3.2.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:30:in `block in process_action'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:25:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:121:in `process'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:45:in `process'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:203:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:246:in `block in action'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:36:in `call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:608:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/etag.rb:23:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/head.rb:14:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/flash.rb:242:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
[bundle].../gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/cookies.rb:341:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/query_cache.rb:64:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `_run__3256550747253976509__call__3432697773279818351__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:32:in `call_app'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/tagged_logging.rb:22:in `tagged'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/request_id.rb:22:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/static.rb:63:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:140:in `forward'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:249:in `fetch'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:189:in `lookup'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:66:in `call!'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:51:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/engine.rb:484:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/application.rb:231:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/railtie/configurable.rb:30:in `method_missing'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/content_length.rb:14:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/log_tailer.rb:17:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/handler/webrick.rb:59:in `service'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/bee90aae008434c67bc5dae3567be852152fe9da/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L138'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/bee90aae008434c67bc5dae3567be852152fe9da/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L94'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/bee90aae008434c67bc5dae3567be852152fe9da/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb#L295'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'</a></pre>
Fingerprint: `4386b5dbbceaf4588e1559d5a56f260a2605190c`

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>May 01, 2016 08:46:28 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/he/witnesses/1375/unassign</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>unassign</td></tr><tr><th>controller</th><td>witnesses</td></tr><tr><th>locale</th><td>he</td></tr><tr><th>id</th><td>1375</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>0dfd5b1935d73315ed635e58959efcaf</td></tr><tr><th>warden.user.user.key</th><td>[[336], &quot;$2a$10$jNKb2x8PKawxyTUoKq82m.&quot;]</td></tr><tr><th>_csrf_token</th><td>GeX+LVggv5W0OuO28gqKNzf0sqDnCkf8LiOmLccyU6E=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/82.81.84.146&#39;&gt;82.81.84.146&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>May 01, 2016 13:22:02 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/he/witnesses/73/unassign</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>unassign</td></tr><tr><th>controller</th><td>witnesses</td></tr><tr><th>locale</th><td>he</td></tr><tr><th>id</th><td>73</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>01ea097d50749e9b25b5ec372c5a51b4</td></tr><tr><th>warden.user.user.key</th><td>[[847], &quot;$2a$10$LF9OjfpGT8XSjZ6jqNs8Ju&quot;]</td></tr><tr><th>_csrf_token</th><td>gI890x8vjx+LYEkj3OStyfORHL5u9kfsn6TVZF7jtvU=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/109.226.28.185&#39;&gt;109.226.28.185&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>May 01, 2016 17:27:36 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/he/witnesses/338/unassign</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>unassign</td></tr><tr><th>controller</th><td>witnesses</td></tr><tr><th>locale</th><td>he</td></tr><tr><th>id</th><td>338</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>3c8ac94c5f29b8d1a4d0b9bfec724022</td></tr><tr><th>warden.user.user.key</th><td>[[2393], &quot;$2a$10$WTqCgx3VpPk85dXmLYxV2e&quot;]</td></tr><tr><th>_csrf_token</th><td>kkztupSVTUvohIPNgvvFQ+uqVeaAldcpj5Z1UR/Jj8U=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/93.172.137.46&#39;&gt;93.172.137.46&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>May 01, 2016 18:44:45 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/he/witnesses/500/unassign</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>unassign</td></tr><tr><th>controller</th><td>witnesses</td></tr><tr><th>locale</th><td>he</td></tr><tr><th>id</th><td>500</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>53ce2265b1f465b35154ae8d078e0a8b</td></tr><tr><th>warden.user.user.key</th><td>[[459], &quot;$2a$10$5IhnK2kfUBcZnCtQHzeCsO&quot;]</td></tr><tr><th>_csrf_token</th><td>MZ0VQ4bwCMYZAwyvOefBZPSZaBRqW1GnwbslzQlntF0=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/80.246.133.232&#39;&gt;80.246.133.232&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip,deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>May 01, 2016 18:44:57 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/he/witnesses/500/unassign</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>unassign</td></tr><tr><th>controller</th><td>witnesses</td></tr><tr><th>locale</th><td>he</td></tr><tr><th>id</th><td>500</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>53ce2265b1f465b35154ae8d078e0a8b</td></tr><tr><th>warden.user.user.key</th><td>[[459], &quot;$2a$10$5IhnK2kfUBcZnCtQHzeCsO&quot;]</td></tr><tr><th>_csrf_token</th><td>MZ0VQ4bwCMYZAwyvOefBZPSZaBRqW1GnwbslzQlntF0=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/80.246.133.232&#39;&gt;80.246.133.232&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip,deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>May 02, 2016 06:13:37 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/he/witnesses/1442/unassign</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>unassign</td></tr><tr><th>controller</th><td>witnesses</td></tr><tr><th>locale</th><td>he</td></tr><tr><th>id</th><td>1442</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>f679f350a8c738df723abb794e98de1e</td></tr><tr><th>warden.user.user.key</th><td>[[336], &quot;$2a$10$jNKb2x8PKawxyTUoKq82m.&quot;]</td></tr><tr><th>_csrf_token</th><td>DepySE9K9QCb0N6O1yQ/EjzOft1AqrVyB10+D9a4mnM=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/79.178.157.224&#39;&gt;79.178.157.224&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>May 02, 2016 14:51:03 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/he/witnesses/1374/unassign</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>unassign</td></tr><tr><th>controller</th><td>witnesses</td></tr><tr><th>locale</th><td>he</td></tr><tr><th>id</th><td>1374</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>92d4b9aee437b37fecd15a8daf5c0ff4</td></tr><tr><th>warden.user.user.key</th><td>[[416], &quot;$2a$10$Oj804eKSJvM8fR85SS4WY.&quot;]</td></tr><tr><th>_csrf_token</th><td>i20m6fbsVPzkavS05vMkN6EcK1hNKHOsK53Z/7MCvSw=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/79.179.2.221&#39;&gt;79.179.2.221&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>May 04, 2016 08:08:17 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/he/witnesses/1749/unassign</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>unassign</td></tr><tr><th>controller</th><td>witnesses</td></tr><tr><th>locale</th><td>he</td></tr><tr><th>id</th><td>1749</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>90d1f0e7c21476ca77ad0a9f22ed259a</td></tr><tr><th>warden.user.user.key</th><td>[[415], &quot;$2a$10$o4dVULl6mn1RipaVGg/Ia.&quot;]</td></tr><tr><th>_csrf_token</th><td>/CMuujFGT/hGnhtevrZsybgTJsyUF7DByn1KsYnNpiM=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/82.81.84.146&#39;&gt;82.81.84.146&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>May 04, 2016 15:10:37 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/he/witnesses/1327/unassign</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>unassign</td></tr><tr><th>controller</th><td>witnesses</td></tr><tr><th>locale</th><td>he</td></tr><tr><th>id</th><td>1327</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>3fb835530ad78be957337795bac9a481</td></tr><tr><th>warden.user.user.key</th><td>[[415], &quot;$2a$10$o4dVULl6mn1RipaVGg/Ia.&quot;]</td></tr><tr><th>_csrf_token</th><td>tMyqDdglYMVklYeXo6Yy/A0Uny/x7ZH/xDoCfdhdgCo=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/82.81.84.146&#39;&gt;82.81.84.146&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>May 04, 2016 15:37:17 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/he/witnesses/1554/unassign</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>unassign</td></tr><tr><th>controller</th><td>witnesses</td></tr><tr><th>locale</th><td>he</td></tr><tr><th>id</th><td>1554</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>3fb835530ad78be957337795bac9a481</td></tr><tr><th>warden.user.user.key</th><td>[[415], &quot;$2a$10$o4dVULl6mn1RipaVGg/Ia.&quot;]</td></tr><tr><th>_csrf_token</th><td>tMyqDdglYMVklYeXo6Yy/A0Uny/x7ZH/xDoCfdhdgCo=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/82.81.84.146&#39;&gt;82.81.84.146&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>
