### ISSUE TITLE
HostsController#index (ActionView::Template::Error) "undefined method `each' for nil:NilClass"

### ISSUE THREAD

**Issue by uriklar** [uriklar/ZikaronBasalon#14]
<table><tr><th>Exception</th><td>undefined method `each&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>April 06, 2015 18:12:13 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/uriklar/ZikaronBasalon/blob/acfaa0383811b4336f875173be9c54cc0af6e176/app/views/hosts/index.html.erb#L44'>[app].../app/views/hosts/index.html.erb:44:in `_app_views_hosts_index_html_erb___3453517700411184279_2219792440'</a>
[bundle].../gems/actionpack-3.2.14/lib/action_view/template.rb:145:in `block in render'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:125:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_view/template.rb:143:in `render'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/template_renderer.rb:48:in `block (2 levels) in render_template'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/template_renderer.rb:47:in `block in render_template'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/template_renderer.rb:55:in `render_with_layout'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/template_renderer.rb:46:in `render_template'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/template_renderer.rb:19:in `render'
[bundle].../gems/newrelic_rpm-3.7.3.204/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:160:in `block in render_with_newrelic'
[bundle].../gems/newrelic_rpm-3.7.3.204/lib/new_relic/agent/method_tracer.rb:281:in `trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.7.3.204/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:159:in `render_with_newrelic'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/renderer.rb:36:in `render_template'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/renderer.rb:17:in `render'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:110:in `_render_template'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/streaming.rb:225:in `_render_template'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:103:in `render_to_body'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:88:in `render'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rendering.rb:16:in `render'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
[bundle].../gems/activesupport-3.2.14/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/Users/rankizi/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
[bundle].../gems/activesupport-3.2.14/lib/active_support/core_ext/benchmark.rb:5:in `ms'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
[bundle].../gems/activerecord-3.2.14/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:39:in `render'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:167:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:436:in `_run__2720752037644487322__process_action__903330483122966165__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:17:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
[bundle].../gems/activerecord-3.2.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/newrelic_rpm-3.7.3.204/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:38:in `block in process_action'
[bundle].../gems/newrelic_rpm-3.7.3.204/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:335:in `perform_action_with_newrelic_trace'
[bundle].../gems/newrelic_rpm-3.7.3.204/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:37:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:121:in `process'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:45:in `process'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:203:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:246:in `block in action'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:36:in `call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:608:in `call'
[bundle].../gems/newrelic_rpm-3.7.3.204/lib/new_relic/rack/error_collector.rb:55:in `call'
[bundle].../gems/newrelic_rpm-3.7.3.204/lib/new_relic/rack/agent_hooks.rb:32:in `call'
[bundle].../gems/newrelic_rpm-3.7.3.204/lib/new_relic/rack/browser_monitoring.rb:27:in `call'
[bundle].../gems/newrelic_rpm-3.7.3.204/lib/new_relic/rack/developer_mode.rb:45:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/head.rb:14:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/flash.rb:242:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
[bundle].../gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/cookies.rb:341:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/query_cache.rb:64:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `_run__1329651068894525319__call__994781798667796541__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/reloader.rb:65:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:32:in `call_app'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/tagged_logging.rb:22:in `tagged'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/request_id.rb:22:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/static.rb:63:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/engine.rb:484:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/application.rb:231:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/log_tailer.rb:17:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/handler/webrick.rb:59:in `service'
/Users/rankizi/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/Users/rankizi/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/Users/rankizi/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'</pre>
Fingerprint: `e4fb8ffa42d845e45f0a082b0cc95d484441cff0`

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 06, 2015 18:12:13 +0000</td></tr><tr><th>URL</th><td>[GET] http://localhost:3000/hosts</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>index</td></tr><tr><th>controller</th><td>hosts</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>9853d3de283ed05e5b8ad9fd1c1d55f7</td></tr><tr><th>_csrf_token</th><td>v8Wgb8GatIvU+ssYx2bTzctgi049jPmXftPHfdTLoA0=</td></tr><tr><th>auth</th><td>extended</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/127.0.0.1&#39;&gt;127.0.0.1&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>
