### ISSUE TITLE
Sidekiq::Extensions::DelayedMailer#default (ActiveRecord::RecordNotFound) "Couldn't find Host with id=203"

### ISSUE THREAD

**Issue by uriklar** [uriklar/ZikaronBasalon#16]
<table><tr><th>Exception</th><td>Couldn&#39;t find Host with id=203</td></tr><tr><th>Last Occurrence</th><td>April 10, 2015 05:52:56 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/activerecord-3.2.14/lib/active_record/relation/finder_methods.rb:344:in `find_one'
[bundle].../gems/activerecord-3.2.14/lib/active_record/relation/finder_methods.rb:315:in `find_with_ids'
[bundle].../gems/activerecord-3.2.14/lib/active_record/relation/finder_methods.rb:107:in `find'
[bundle].../gems/activerecord-3.2.14/lib/active_record/querying.rb:5:in `find'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/77c02ed8863850b3a864d0d0bb3475ca808df665/app/mailers/host_mailer.rb#L9'>[app].../app/mailers/host_mailer.rb:9:in `manager_notification'</a>
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:167:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:121:in `process'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:45:in `process'
[bundle].../gems/actionmailer-3.2.14/lib/action_mailer/base.rb:459:in `process'
[bundle].../gems/actionmailer-3.2.14/lib/action_mailer/base.rb:453:in `initialize'
[bundle].../gems/actionmailer-3.2.14/lib/action_mailer/base.rb:439:in `new'
[bundle].../gems/actionmailer-3.2.14/lib/action_mailer/base.rb:439:in `method_missing'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/extensions/action_mailer.rb:17:in `public_send'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/extensions/action_mailer.rb:17:in `perform'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:75:in `execute_job'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/77c02ed8863850b3a864d0d0bb3475ca808df665/config/initializers/party_foul_sidekiq.rb#L5'>[app].../config/initializers/party_foul_sidekiq.rb:5:in `call'</a>
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
[bundle].../gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
[bundle].../gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:353:in `perform_action_with_newrelic_trace'
[bundle].../gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/logging.rb:24:in `with_context'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/logging.rb:7:in `call'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:132:in `call'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:132:in `invoke'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:51:in `block in process'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:98:in `stats'
[bundle].../gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:50:in `process'
[bundle].../gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
[bundle].../gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
[bundle].../gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
[bundle].../gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
[bundle].../gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
[bundle].../gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
[bundle].../gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
[bundle].../gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'</pre>
Fingerprint: `3f95c59b8c4254f025406ec489c79e0fc19fb71a`

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 10, 2015 05:52:56 +0000</td></tr><tr><th>Params</th><td><table><tr><th>retry</th><td>true</td></tr><tr><th>queue</th><td>default</td></tr><tr><th>class</th><td>Sidekiq::Extensions::DelayedMailer</td></tr><tr><th>args</th><td>[&quot;---\n- !ruby/class &#39;HostMailer&#39;\n- :manager_notification\n- - Nissimmi@gmail.com\n  - 203\n&quot;]</td></tr><tr><th>jid</th><td>64d415d3572eaa1516f038ff</td></tr><tr><th>enqueued_at</th><td>1426876888.700618</td></tr><tr><th>error_message</th><td>Couldn&#39;t find Host with id=203</td></tr><tr><th>error_class</th><td>ActiveRecord::RecordNotFound</td></tr><tr><th>failed_at</th><td>1426876888.7800183</td></tr><tr><th>retry_count</th><td>24</td></tr><tr><th>retried_at</th><td>1428313284.012859</td></tr></table></td></tr></table>
