### ISSUE TITLE
PagesController#home (I18n::InvalidLocale) ""he hasGoogleVoiceExt" is not a valid locale"

### ISSUE THREAD

**Issue by uriklar** [uriklar/ZikaronBasalon#18]
<table><tr><th>Exception</th><td>&quot;he hasGoogleVoiceExt&quot; is not a valid locale</td></tr><tr><th>Last Occurrence</th><td>April 11, 2015 21:11:53 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/i18n-0.7.0/lib/i18n.rb:284:in `enforce_available_locales!'
[bundle].../gems/i18n-0.7.0/lib/i18n/config.rb:13:in `locale='
[bundle].../gems/actionpack-3.2.14/lib/action_view/lookup_context.rb:228:in `locale='
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:29:in `locale='
[bundle].../gems/i18n-0.7.0/lib/i18n.rb:35:in `locale='
<a href='https://github.com/uriklar/ZikaronBasalon/blob/dc941babb35eba58509cbe859cb14021b86f5e02/app/controllers/application_controller.rb#L15'>[app].../app/controllers/application_controller.rb:15:in `set_locale'</a>
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:418:in `_run__4480166043930022327__process_action__2541760294506250634__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:17:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
[bundle].../gems/activerecord-3.2.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:23:in `block in process_action'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:353:in `perform_action_with_newrelic_trace'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:22:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:121:in `process'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:45:in `process'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:203:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:246:in `block in action'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:36:in `call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:608:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/head.rb:14:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/flash.rb:242:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
[bundle].../gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/cookies.rb:341:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/query_cache.rb:64:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `_run__2983633319827787345__call__1376684650276432051__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:32:in `call_app'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/tagged_logging.rb:22:in `tagged'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/request_id.rb:22:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/static.rb:63:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/engine.rb:484:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/application.rb:231:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/railtie/configurable.rb:30:in `method_missing'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/log_tailer.rb:17:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/handler/webrick.rb:59:in `service'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/dc941babb35eba58509cbe859cb14021b86f5e02/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L138'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/dc941babb35eba58509cbe859cb14021b86f5e02/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L94'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/dc941babb35eba58509cbe859cb14021b86f5e02/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb#L295'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'</a></pre>
Fingerprint: `1fb53c3f0ac005ffb947f85119e84c1a6fac2835`

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 11, 2015 21:11:53 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/pages/home.js?city_id=120&amp;locale=he+hasGoogleVoiceExt</td></tr><tr><th>Params</th><td><table><tr><th>city_id</th><td>120</td></tr><tr><th>locale</th><td>he hasGoogleVoiceExt</td></tr><tr><th>controller</th><td>pages</td></tr><tr><th>action</th><td>home</td></tr><tr><th>format</th><td>js</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>4d0d8e2172ec9b76ab86349ee6c89e8d</td></tr><tr><th>_csrf_token</th><td>rhoaD1rc7zAUYUe2PQR7ClNJanNdJPdW2cRP91gsHX4=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/76.182.73.71&#39;&gt;76.182.73.71&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>*/*</td></tr></table></td></tr></table>
