### ISSUE TITLE
HostsController#send_request (ActiveRecord::StatementInvalid) "PGError: ERROR:  value "5255645421" is out of range for type integer
: INSERT INTO "guests" ("created_at", "email", "name", "num_of_friends", "phone", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id""

### ISSUE THREAD

**Issue by uriklar** [uriklar/ZikaronBasalon#22]
<table><tr><th>Exception</th><td>PGError: ERROR:  value &quot;5255645421&quot; is out of range for type integer
: INSERT INTO &quot;guests&quot; (&quot;created_at&quot;, &quot;email&quot;, &quot;name&quot;, &quot;num_of_friends&quot;, &quot;phone&quot;, &quot;updated_at&quot;) VALUES ($1, $2, $3, $4, $5, $6) RETURNING &quot;id&quot;</td></tr><tr><th>Last Occurrence</th><td>April 15, 2015 09:26:58 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `get_last_result'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `exec_cache'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `block in exec_query'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/active_record.rb:55:in `block in log_with_newrelic_instrumentation'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/method_tracer.rb:69:in `block in trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/method_tracer.rb:67:in `trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/active_record.rb:52:in `log_with_newrelic_instrumentation'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `exec_query'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/database_statements.rb:63:in `exec_insert'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/database_statements.rb:90:in `insert'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
[bundle].../gems/activerecord-3.2.14/lib/active_record/relation.rb:66:in `insert'
[bundle].../gems/activerecord-3.2.14/lib/active_record/persistence.rb:367:in `create'
[bundle].../gems/activerecord-3.2.14/lib/active_record/timestamp.rb:58:in `create'
[bundle].../gems/activerecord-3.2.14/lib/active_record/callbacks.rb:268:in `block in create'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:403:in `_run__1737828232139367409__create__3674703404851678790__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/activerecord-3.2.14/lib/active_record/callbacks.rb:268:in `create'
[bundle].../gems/activerecord-3.2.14/lib/active_record/persistence.rb:348:in `create_or_update'
[bundle].../gems/activerecord-3.2.14/lib/active_record/callbacks.rb:264:in `block in create_or_update'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:414:in `_run__1737828232139367409__save__3674703404851678790__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/activerecord-3.2.14/lib/active_record/callbacks.rb:264:in `create_or_update'
[bundle].../gems/activerecord-3.2.14/lib/active_record/persistence.rb:84:in `save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/validations.rb:50:in `save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/attribute_methods/dirty.rb:22:in `save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:259:in `block (2 levels) in save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:208:in `transaction'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:259:in `block in save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:258:in `save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/relation/finder_methods.rb:297:in `find_or_instantiator_by_attributes'
[bundle].../gems/activerecord-3.2.14/lib/active_record/dynamic_matchers.rb:52:in `method_missing'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/2e00af60f9770fe1dad065ea6b2491b43982d92d/app/controllers/hosts_controller.rb#L64'>[app].../app/controllers/hosts_controller.rb:64:in `send_request'</a>
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:167:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:425:in `_run__621469948909945978__process_action__750679706993052764__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:17:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
[bundle].../gems/activerecord-3.2.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:23:in `block in process_action'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:353:in `perform_action_with_newrelic_trace'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:22:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:121:in `process'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:45:in `process'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:203:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:246:in `block in action'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:36:in `call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:608:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/conditionalget.rb:35:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/head.rb:14:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/flash.rb:242:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
[bundle].../gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/cookies.rb:341:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/query_cache.rb:64:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `_run__3530460796804054567__call__3674703404851678790__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:32:in `call_app'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/tagged_logging.rb:22:in `tagged'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/request_id.rb:22:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/static.rb:63:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:143:in `pass'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:155:in `invalidate'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:71:in `call!'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/engine.rb:484:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/application.rb:231:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/railtie/configurable.rb:30:in `method_missing'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/log_tailer.rb:17:in `call'
[bundle].../gems/rack-1.4.5/lib/rack/handler/webrick.rb:59:in `service'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/2e00af60f9770fe1dad065ea6b2491b43982d92d/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L138'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/2e00af60f9770fe1dad065ea6b2491b43982d92d/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L94'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/2e00af60f9770fe1dad065ea6b2491b43982d92d/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb#L295'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'</a></pre>
Fingerprint: `d1d3868aa26eedcd43be821f219c154d70badbb2`

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 15, 2015 09:26:58 +0000</td></tr><tr><th>URL</th><td>[POST] http://zikaronbasalon.herokuapp.com/he/hosts/send_request</td></tr><tr><th>Params</th><td><table><tr><th>utf8</th><td>✓</td></tr><tr><th>authenticity_token</th><td>Z9I0ec9kGKTAPU4+uESg7kqInYhQKOSKPE163SfGeoQ=</td></tr><tr><th>guest</th><td><table><tr><th>name</th><td>שירה דוד</td></tr><tr><th>email</th><td>05255645421</td></tr><tr><th>phone</th><td>05255645421</td></tr><tr><th>num_of_friends</th><td>05255645421</td></tr><tr><th>host_id</th><td>41</td></tr></table></td></tr><tr><th>commit</th><td>שלח</td></tr><tr><th>controller</th><td>hosts</td></tr><tr><th>action</th><td>send_request</td></tr><tr><th>locale</th><td>he</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>1ff1b5bae22542e62559f9a66363b5c6</td></tr><tr><th>_csrf_token</th><td>Z9I0ec9kGKTAPU4+uESg7kqInYhQKOSKPE163SfGeoQ=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/84.95.255.154&#39;&gt;84.95.255.154&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html, application/xhtml+xml, */*</td></tr></table></td></tr></table>
