### ISSUE TITLE
HostsController#create (ActiveRecord::StatementInvalid) "PGError: ERROR:  permission denied for relation cities
: INSERT INTO "cities" ("created_at", "manager_email", "name", "region_id", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id""

### ISSUE THREAD

**Issue by uriklar** [uriklar/ZikaronBasalon#27]
<table><tr><th>Exception</th><td>PGError: ERROR:  permission denied for relation cities
: INSERT INTO &quot;cities&quot; (&quot;created_at&quot;, &quot;manager_email&quot;, &quot;name&quot;, &quot;region_id&quot;, &quot;updated_at&quot;) VALUES ($1, $2, $3, $4, $5) RETURNING &quot;id&quot;</td></tr><tr><th>Last Occurrence</th><td>November 19, 2015 08:45:28 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `get_last_result'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `exec_cache'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `block in exec_query'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/active_record.rb:59:in `block in log_with_newrelic_instrumentation'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/active_record.rb:56:in `log_with_newrelic_instrumentation'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `exec_query'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/database_statements.rb:63:in `exec_insert'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/database_statements.rb:90:in `insert'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
[bundle].../gems/activerecord-3.2.14/lib/active_record/relation.rb:66:in `insert'
[bundle].../gems/activerecord-3.2.14/lib/active_record/persistence.rb:367:in `create'
[bundle].../gems/activerecord-3.2.14/lib/active_record/timestamp.rb:58:in `create'
[bundle].../gems/activerecord-3.2.14/lib/active_record/callbacks.rb:268:in `block in create'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:403:in `_run__544899613849142877__create__4235422692877260236__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/activerecord-3.2.14/lib/active_record/callbacks.rb:268:in `create'
[bundle].../gems/activerecord-3.2.14/lib/active_record/persistence.rb:348:in `create_or_update'
[bundle].../gems/activerecord-3.2.14/lib/active_record/callbacks.rb:264:in `block in create_or_update'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:425:in `_run__544899613849142877__save__4235422692877260236__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/activerecord-3.2.14/lib/active_record/callbacks.rb:264:in `create_or_update'
[bundle].../gems/activerecord-3.2.14/lib/active_record/persistence.rb:84:in `save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/validations.rb:50:in `save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/attribute_methods/dirty.rb:22:in `save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:259:in `block (2 levels) in save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:208:in `transaction'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:259:in `block in save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
[bundle].../gems/activerecord-3.2.14/lib/active_record/transactions.rb:258:in `save'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/active_record_helper.rb:21:in `block in save'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/transaction.rb:807:in `with_database_metric_name'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent.rb:572:in `with_database_metric_name'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/active_record_helper.rb:20:in `save'
[bundle].../gems/activerecord-3.2.14/lib/active_record/relation/finder_methods.rb:297:in `find_or_instantiator_by_attributes'
[bundle].../gems/activerecord-3.2.14/lib/active_record/dynamic_matchers.rb:52:in `method_missing'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/de9ea5feb5bdb378ebb64cd10833ecee0fb0f986/app/models/host.rb#L35'>[app].../app/models/host.rb:35:in `city_name='</a>
[bundle].../gems/activerecord-3.2.14/lib/active_record/attribute_assignment.rb:85:in `block in assign_attributes'
[bundle].../gems/activerecord-3.2.14/lib/active_record/attribute_assignment.rb:78:in `each'
[bundle].../gems/activerecord-3.2.14/lib/active_record/attribute_assignment.rb:78:in `assign_attributes'
[bundle].../gems/activerecord-3.2.14/lib/active_record/base.rb:498:in `initialize'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/de9ea5feb5bdb378ebb64cd10833ecee0fb0f986/app/controllers/hosts_controller.rb#L14'>[app].../app/controllers/hosts_controller.rb:14:in `new'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/de9ea5feb5bdb378ebb64cd10833ecee0fb0f986/app/controllers/hosts_controller.rb#L14'>[app].../app/controllers/hosts_controller.rb:14:in `create'</a>
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:167:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:425:in `_run__4566190198624329467__process_action__2677528956240759552__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:17:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
[bundle].../gems/activerecord-3.2.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:30:in `block in process_action'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:25:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:121:in `process'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:45:in `process'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:203:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:246:in `block in action'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:36:in `call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:608:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/etag.rb:23:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/conditionalget.rb:35:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/head.rb:14:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/flash.rb:242:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
[bundle].../gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/cookies.rb:341:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/query_cache.rb:64:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `_run__497416436327467821__call__4235422692877260236__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:32:in `call_app'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/tagged_logging.rb:22:in `tagged'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/request_id.rb:22:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/static.rb:63:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:143:in `pass'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:155:in `invalidate'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:71:in `call!'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/engine.rb:484:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/application.rb:231:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/railtie/configurable.rb:30:in `method_missing'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/content_length.rb:14:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/log_tailer.rb:17:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/handler/webrick.rb:59:in `service'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/de9ea5feb5bdb378ebb64cd10833ecee0fb0f986/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L138'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/de9ea5feb5bdb378ebb64cd10833ecee0fb0f986/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L94'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/de9ea5feb5bdb378ebb64cd10833ecee0fb0f986/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb#L295'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'</a></pre>
Fingerprint: `11a2408c493565e97cbcda0cd431b734daeea097`

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>November 19, 2015 08:45:28 +0000</td></tr><tr><th>URL</th><td>[POST] http://zikaronbasalon.herokuapp.com/he/hosts</td></tr><tr><th>Params</th><td><table><tr><th>utf8</th><td>✓</td></tr><tr><th>authenticity_token</th><td>1lICA0ujUgsBy47dcSUb0s7W+XgJwsH8vts8x4nZ/F0=</td></tr><tr><th>host</th><td><table><tr><th>f_name</th><td>תדהר</td></tr><tr><th>l_name</th><td>שמעוני</td></tr><tr><th>email</th><td>matn10124@gmail/com</td></tr><tr><th>phone</th><td>0526071002</td></tr><tr><th>address</th><td>אפרת</td></tr><tr><th>city_name</th><td>אפרת</td></tr><tr><th>lat</th><td>31.653589</td></tr><tr><th>lng</th><td>35.14993400000003</td></tr><tr><th>strangers</th><td>true</td></tr><tr><th>max_guests</th><td>10-100</td></tr><tr><th>date</th><td></td></tr><tr><th>free_text</th><td>שלום רב! אנחנו מתנ&quot;ס אפרת מעוניינים לארח אפשרי בבתים של תושבים שאנו נדאג לאירוח ולתיאום כמו כן אפשר באולמות שיש לנו ברחבי אפרת. אנו מארחים למופת ונשח אם נוכל לארח ביישובנו. אפשרי בכל עת בשנה ולאו דווקא בסמיכות ליום הזיכרון. תודה רבה </td></tr></table></td></tr><tr><th>commit</th><td>שלח/י</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>hosts</td></tr><tr><th>locale</th><td>he</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>81df07c9e52a86c638884d98db613e2f</td></tr><tr><th>_csrf_token</th><td>1lICA0ujUgsBy47dcSUb0s7W+XgJwsH8vts8x4nZ/F0=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/31.168.241.139&#39;&gt;31.168.241.139&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html, application/xhtml+xml, */*</td></tr></table></td></tr></table>
