### ISSUE TITLE
PagesController#home (ActionView::Template::Error) "PGError: ERROR:  relation "hosts" does not exist
LINE 1: SELECT  "hosts".* FROM "hosts"  WHERE "hosts"."strangers" = ...
                               ^
: SELECT  "hosts".* FROM "hosts"  WHERE "hosts"."strangers" = 't' AND ("hosts"."max_guests" BETWEEN 1 AND 9999) LIMIT 10 OFFSET 0"

### ISSUE THREAD

**Issue by uriklar** [uriklar/ZikaronBasalon#31]
<table><tr><th>Exception</th><td>PGError: ERROR:  relation &quot;hosts&quot; does not exist
LINE 1: SELECT  &quot;hosts&quot;.* FROM &quot;hosts&quot;  WHERE &quot;hosts&quot;.&quot;strangers&quot; = ...
                               ^
: SELECT  &quot;hosts&quot;.* FROM &quot;hosts&quot;  WHERE &quot;hosts&quot;.&quot;strangers&quot; = &#39;t&#39; AND (&quot;hosts&quot;.&quot;max_guests&quot; BETWEEN 1 AND 9999) LIMIT 10 OFFSET 0</td></tr><tr><th>Last Occurrence</th><td>March 03, 2016 06:10:04 +0000</td></tr><tr><th>Count</th><td>6</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.rb:1163:in `async_exec'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.rb:1163:in `exec_no_cache'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.rb:660:in `block in exec_query'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/active_record.rb:59:in `block in log_with_newrelic_instrumentation'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/active_record.rb:56:in `log_with_newrelic_instrumentation'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `exec_query'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.rb:1262:in `select'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/query_cache.rb:61:in `block in select_all'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/query_cache.rb:75:in `cache_sql'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/query_cache.rb:61:in `select_all'
[bundle].../gems/activerecord-3.2.14/lib/active_record/querying.rb:38:in `block in find_by_sql'
[bundle].../gems/activerecord-3.2.14/lib/active_record/explain.rb:41:in `logging_query_plan'
[bundle].../gems/activerecord-3.2.14/lib/active_record/querying.rb:37:in `find_by_sql'
[bundle].../gems/activerecord-3.2.14/lib/active_record/relation.rb:171:in `exec_queries'
[bundle].../gems/activerecord-3.2.14/lib/active_record/relation.rb:160:in `block in to_a'
[bundle].../gems/activerecord-3.2.14/lib/active_record/explain.rb:41:in `logging_query_plan'
[bundle].../gems/activerecord-3.2.14/lib/active_record/relation.rb:159:in `to_a'
[bundle].../gems/activerecord-3.2.14/lib/active_record/relation/delegation.rb:6:in `each'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/e3b5f8e04ee19a3a0440cbeef8098bfab212f3c2/app/views/hosts/_hosts.html.erb#L1'>[app].../app/views/hosts/_hosts.html.erb:1:in `_app_views_hosts__hosts_html_erb___138875531337973602_70052652178120'</a>
[bundle].../gems/actionpack-3.2.14/lib/action_view/template.rb:145:in `block in render'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:125:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_view/template.rb:143:in `render'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:167:in `block in instrument_with_newrelic'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:166:in `instrument_with_newrelic'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/partial_renderer.rb:237:in `render'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/renderer.rb:41:in `render_partial'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/renderer.rb:15:in `render'
[bundle].../gems/actionpack-3.2.14/lib/action_view/helpers/rendering_helper.rb:24:in `render'
[bundle].../gems/haml-4.0.7/lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/e3b5f8e04ee19a3a0440cbeef8098bfab212f3c2/app/views/pages/home.js.erb#L4'>[app].../app/views/pages/home.js.erb:4:in `_app_views_pages_home_js_erb___3995730028007015857_70052651661320'</a>
[bundle].../gems/actionpack-3.2.14/lib/action_view/template.rb:145:in `block in render'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:125:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_view/template.rb:143:in `render'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/template_renderer.rb:48:in `block (2 levels) in render_template'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/template_renderer.rb:47:in `block in render_template'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/template_renderer.rb:55:in `render_with_layout'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/template_renderer.rb:46:in `render_template'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/template_renderer.rb:19:in `render'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:152:in `block in render_with_newrelic'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:151:in `render_with_newrelic'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/renderer.rb:36:in `render_template'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/renderer.rb:17:in `render'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:110:in `_render_template'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/streaming.rb:225:in `_render_template'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:103:in `render_to_body'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:88:in `render'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rendering.rb:16:in `render'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
[bundle].../gems/activesupport-3.2.14/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/e3b5f8e04ee19a3a0440cbeef8098bfab212f3c2/vendor/ruby-2.0.0/lib/ruby/2.0.0/benchmark.rb#L296'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'</a>
[bundle].../gems/activesupport-3.2.14/lib/active_support/core_ext/benchmark.rb:5:in `ms'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
[bundle].../gems/activerecord-3.2.14/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:39:in `render'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/mime_responds.rb:196:in `respond_to'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/e3b5f8e04ee19a3a0440cbeef8098bfab212f3c2/app/controllers/pages_controller.rb#L8'>[app].../app/controllers/pages_controller.rb:8:in `home'</a>
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:167:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:425:in `_run__107327608428679784__process_action__3588600847053094996__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:17:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
[bundle].../gems/activerecord-3.2.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:30:in `block in process_action'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:25:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:121:in `process'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:45:in `process'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:203:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:246:in `block in action'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:36:in `call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:608:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/etag.rb:23:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/head.rb:14:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/flash.rb:242:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
[bundle].../gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/cookies.rb:341:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/query_cache.rb:64:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `_run__1909899042453611299__call__2331406104979092869__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:32:in `call_app'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/tagged_logging.rb:22:in `tagged'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/request_id.rb:22:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/static.rb:63:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
[bundle].../gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/engine.rb:484:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/application.rb:231:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/railtie/configurable.rb:30:in `method_missing'
[bundle].../gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/content_length.rb:14:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/log_tailer.rb:17:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/handler/webrick.rb:59:in `service'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/e3b5f8e04ee19a3a0440cbeef8098bfab212f3c2/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L138'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/e3b5f8e04ee19a3a0440cbeef8098bfab212f3c2/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L94'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/e3b5f8e04ee19a3a0440cbeef8098bfab212f3c2/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb#L295'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'</a></pre>
Fingerprint: `ef0cbfef91e5ee031d5ecc48d6872385a846c023`

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>March 03, 2016 06:08:19 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/</td></tr><tr><th>Params</th><td><table><tr><th>controller</th><td>pages</td></tr><tr><th>action</th><td>home</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/54.247.188.179&#39;&gt;54.247.188.179&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>NewRelicPinger/1.0 (641046)</td></tr><tr><th>Accept Encoding</th><td></td></tr><tr><th>Accept</th><td>*/*</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>March 03, 2016 06:08:26 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/</td></tr><tr><th>Params</th><td><table><tr><th>controller</th><td>pages</td></tr><tr><th>action</th><td>home</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/54.251.34.67&#39;&gt;54.251.34.67&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>NewRelicPinger/1.0 (641046)</td></tr><tr><th>Accept Encoding</th><td></td></tr><tr><th>Accept</th><td>*/*</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>March 03, 2016 06:09:24 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/</td></tr><tr><th>Params</th><td><table><tr><th>controller</th><td>pages</td></tr><tr><th>action</th><td>home</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/50.112.95.211&#39;&gt;50.112.95.211&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>NewRelicPinger/1.0 (641046)</td></tr><tr><th>Accept Encoding</th><td></td></tr><tr><th>Accept</th><td>*/*</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>March 03, 2016 06:09:34 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/</td></tr><tr><th>Params</th><td><table><tr><th>controller</th><td>pages</td></tr><tr><th>action</th><td>home</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/184.73.237.85&#39;&gt;184.73.237.85&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>NewRelicPinger/1.0 (641046)</td></tr><tr><th>Accept Encoding</th><td></td></tr><tr><th>Accept</th><td>*/*</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>March 03, 2016 06:09:47 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/</td></tr><tr><th>Params</th><td><table><tr><th>controller</th><td>pages</td></tr><tr><th>action</th><td>home</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/54.248.250.232&#39;&gt;54.248.250.232&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>NewRelicPinger/1.0 (641046)</td></tr><tr><th>Accept Encoding</th><td></td></tr><tr><th>Accept</th><td>*/*</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>March 03, 2016 06:10:04 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/</td></tr><tr><th>Params</th><td><table><tr><th>controller</th><td>pages</td></tr><tr><th>action</th><td>home</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/50.31.164.139&#39;&gt;50.31.164.139&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>NewRelicPinger/1.0 (641046)</td></tr><tr><th>Accept Encoding</th><td></td></tr><tr><th>Accept</th><td>*/*</td></tr></table></td></tr></table>
