### ISSUE TITLE
ManagersController#remove_city (NoMethodError) "undefined method `destroy' for nil:NilClass"

### ISSUE THREAD

**Issue by uriklar** [uriklar/ZikaronBasalon#40]
<table><tr><th>Exception</th><td>undefined method `destroy&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>April 18, 2016 11:41:30 +0000</td></tr><tr><th>Count</th><td>7</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/uriklar/ZikaronBasalon/blob/dc2faad7e93dfacf801d9110e989532b3fc32816/app/controllers/managers_controller.rb#L65'>[app].../app/controllers/managers_controller.rb:65:in `remove_city'</a>
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:167:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:436:in `_run__1084484043031498730__process_action__1289207487880719017__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:17:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
[bundle].../gems/activerecord-3.2.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:30:in `block in process_action'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:25:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:121:in `process'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:45:in `process'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:203:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:246:in `block in action'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:36:in `call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:608:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/etag.rb:23:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/conditionalget.rb:35:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/head.rb:14:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/flash.rb:242:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
[bundle].../gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/cookies.rb:341:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/query_cache.rb:64:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `_run__2950446479684497095__call__1380203055803826778__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:32:in `call_app'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/tagged_logging.rb:22:in `tagged'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/request_id.rb:22:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/static.rb:63:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:140:in `forward'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:147:in `pass'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:159:in `invalidate'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:74:in `call!'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:51:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/engine.rb:484:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/application.rb:231:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/railtie/configurable.rb:30:in `method_missing'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/content_length.rb:14:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/log_tailer.rb:17:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/handler/webrick.rb:59:in `service'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/dc2faad7e93dfacf801d9110e989532b3fc32816/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L138'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/dc2faad7e93dfacf801d9110e989532b3fc32816/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L94'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/dc2faad7e93dfacf801d9110e989532b3fc32816/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb#L295'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'</a></pre>
Fingerprint: `5ad7d941f200d843043eb2f1a2e31f4a7d1a1d89`

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>March 15, 2016 13:21:55 +0000</td></tr><tr><th>URL</th><td>[POST] http://zikaronbasalon.herokuapp.com/managers/2/remove_city</td></tr><tr><th>Params</th><td><table><tr><th>city_id</th><td>6</td></tr><tr><th>action</th><td>remove_city</td></tr><tr><th>controller</th><td>managers</td></tr><tr><th>id</th><td>2</td></tr><tr><th>manager</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>3848b7db24d64be2e47b0485f483af29</td></tr><tr><th>warden.user.user.key</th><td>[[1], &quot;$2a$10$cK5NKoFZ0/6GYRoS8Xqj1O&quot;]</td></tr><tr><th>_csrf_token</th><td>o1bt9ObmsUuZEi4qiheWBC7wfdm6pAv1SlXzpvLPQUY=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/82.81.84.146&#39;&gt;82.81.84.146&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>application/json, text/plain, */*</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 12, 2016 14:03:55 +0000</td></tr><tr><th>URL</th><td>[POST] http://zikaronbasalon.herokuapp.com/managers/32/remove_city</td></tr><tr><th>Params</th><td><table><tr><th>city_id</th><td>392</td></tr><tr><th>action</th><td>remove_city</td></tr><tr><th>controller</th><td>managers</td></tr><tr><th>id</th><td>32</td></tr><tr><th>manager</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>19f7bda62b5eb511dca1e2dba3a9bbc2</td></tr><tr><th>warden.user.user.key</th><td>[[415], &quot;$2a$10$o4dVULl6mn1RipaVGg/Ia.&quot;]</td></tr><tr><th>_csrf_token</th><td>LOV6CAXjLJPoOiPCg5zMhzARrcmlEf0a8T2qDBCioOI=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/79.178.32.25&#39;&gt;79.178.32.25&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>application/json, text/plain, */*</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 12, 2016 14:04:01 +0000</td></tr><tr><th>URL</th><td>[POST] http://zikaronbasalon.herokuapp.com/managers/32/remove_city</td></tr><tr><th>Params</th><td><table><tr><th>city_id</th><td>392</td></tr><tr><th>action</th><td>remove_city</td></tr><tr><th>controller</th><td>managers</td></tr><tr><th>id</th><td>32</td></tr><tr><th>manager</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>19f7bda62b5eb511dca1e2dba3a9bbc2</td></tr><tr><th>warden.user.user.key</th><td>[[415], &quot;$2a$10$o4dVULl6mn1RipaVGg/Ia.&quot;]</td></tr><tr><th>_csrf_token</th><td>LOV6CAXjLJPoOiPCg5zMhzARrcmlEf0a8T2qDBCioOI=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/79.178.32.25&#39;&gt;79.178.32.25&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>application/json, text/plain, */*</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 12, 2016 14:04:02 +0000</td></tr><tr><th>URL</th><td>[POST] http://zikaronbasalon.herokuapp.com/managers/32/remove_city</td></tr><tr><th>Params</th><td><table><tr><th>city_id</th><td>392</td></tr><tr><th>action</th><td>remove_city</td></tr><tr><th>controller</th><td>managers</td></tr><tr><th>id</th><td>32</td></tr><tr><th>manager</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>19f7bda62b5eb511dca1e2dba3a9bbc2</td></tr><tr><th>warden.user.user.key</th><td>[[415], &quot;$2a$10$o4dVULl6mn1RipaVGg/Ia.&quot;]</td></tr><tr><th>_csrf_token</th><td>LOV6CAXjLJPoOiPCg5zMhzARrcmlEf0a8T2qDBCioOI=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/79.178.32.25&#39;&gt;79.178.32.25&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>application/json, text/plain, */*</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 14, 2016 10:28:05 +0000</td></tr><tr><th>URL</th><td>[POST] http://zikaronbasalon.herokuapp.com/managers/69/remove_city</td></tr><tr><th>Params</th><td><table><tr><th>city_id</th><td>390</td></tr><tr><th>action</th><td>remove_city</td></tr><tr><th>controller</th><td>managers</td></tr><tr><th>id</th><td>69</td></tr><tr><th>manager</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>c6cf4eaf2f24405d2d3ad8063b6d2e0b</td></tr><tr><th>warden.user.user.key</th><td>[[415], &quot;$2a$10$o4dVULl6mn1RipaVGg/Ia.&quot;]</td></tr><tr><th>_csrf_token</th><td>ESYXUETYTWA03VTg5xv9O+DB8+xy/rjh2L2/lpkKBVY=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/82.81.84.146&#39;&gt;82.81.84.146&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>application/json, text/plain, */*</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 14, 2016 10:28:05 +0000</td></tr><tr><th>URL</th><td>[POST] http://zikaronbasalon.herokuapp.com/managers/69/remove_city</td></tr><tr><th>Params</th><td><table><tr><th>city_id</th><td>390</td></tr><tr><th>action</th><td>remove_city</td></tr><tr><th>controller</th><td>managers</td></tr><tr><th>id</th><td>69</td></tr><tr><th>manager</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>c6cf4eaf2f24405d2d3ad8063b6d2e0b</td></tr><tr><th>warden.user.user.key</th><td>[[415], &quot;$2a$10$o4dVULl6mn1RipaVGg/Ia.&quot;]</td></tr><tr><th>_csrf_token</th><td>ESYXUETYTWA03VTg5xv9O+DB8+xy/rjh2L2/lpkKBVY=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/82.81.84.146&#39;&gt;82.81.84.146&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>application/json, text/plain, */*</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 18, 2016 11:41:30 +0000</td></tr><tr><th>URL</th><td>[POST] http://zikaronbasalon.herokuapp.com/managers/27/remove_city</td></tr><tr><th>Params</th><td><table><tr><th>city_id</th><td>767</td></tr><tr><th>action</th><td>remove_city</td></tr><tr><th>controller</th><td>managers</td></tr><tr><th>id</th><td>27</td></tr><tr><th>manager</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>b62d9efa017035aedd6be67baf58a7bb</td></tr><tr><th>warden.user.user.key</th><td>[[415], &quot;$2a$10$o4dVULl6mn1RipaVGg/Ia.&quot;]</td></tr><tr><th>_csrf_token</th><td>Ffxx9xPRxCAI5+W2CbXT3yGqgjZC9bcSesJSccwTNRc=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/82.81.84.146&#39;&gt;82.81.84.146&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>application/json, text/plain, */*</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 18, 2016 11:41:31 +0000</td></tr><tr><th>URL</th><td>[POST] http://zikaronbasalon.herokuapp.com/managers/27/remove_city</td></tr><tr><th>Params</th><td><table><tr><th>city_id</th><td>767</td></tr><tr><th>action</th><td>remove_city</td></tr><tr><th>controller</th><td>managers</td></tr><tr><th>id</th><td>27</td></tr><tr><th>manager</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>b62d9efa017035aedd6be67baf58a7bb</td></tr><tr><th>warden.user.user.key</th><td>[[415], &quot;$2a$10$o4dVULl6mn1RipaVGg/Ia.&quot;]</td></tr><tr><th>_csrf_token</th><td>Ffxx9xPRxCAI5+W2CbXT3yGqgjZC9bcSesJSccwTNRc=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/82.81.84.146&#39;&gt;82.81.84.146&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>application/json, text/plain, */*</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>April 18, 2016 11:41:32 +0000</td></tr><tr><th>URL</th><td>[POST] http://zikaronbasalon.herokuapp.com/managers/27/remove_city</td></tr><tr><th>Params</th><td><table><tr><th>city_id</th><td>767</td></tr><tr><th>action</th><td>remove_city</td></tr><tr><th>controller</th><td>managers</td></tr><tr><th>id</th><td>27</td></tr><tr><th>manager</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>b62d9efa017035aedd6be67baf58a7bb</td></tr><tr><th>warden.user.user.key</th><td>[[415], &quot;$2a$10$o4dVULl6mn1RipaVGg/Ia.&quot;]</td></tr><tr><th>_csrf_token</th><td>Ffxx9xPRxCAI5+W2CbXT3yGqgjZC9bcSesJSccwTNRc=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/82.81.84.146&#39;&gt;82.81.84.146&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>application/json, text/plain, */*</td></tr></table></td></tr></table>
