### ISSUE TITLE
RegistrationsController#create (ActionDispatch::RemoteIp::IpSpoofAttackError) "IP spoofing attack?!HTTP_CLIENT_IP="10.20.48.81"HTTP_X_FORWARDED_FOR="10.20.48.81, 81.218.97.45""

### ISSUE THREAD

**Issue by uriklar** [uriklar/ZikaronBasalon#41]
<table><tr><th>Exception</th><td>IP spoofing attack?!HTTP_CLIENT_IP=&quot;10.20.48.81&quot;HTTP_X_FORWARDED_FOR=&quot;10.20.48.81, 81.218.97.45&quot;</td></tr><tr><th>Last Occurrence</th><td>March 15, 2016 14:34:17 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/remote_ip.rb:55:in `calculate_ip'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/remote_ip.rb:69:in `to_s'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/http/request.rb:165:in `remote_ip'
[bundle].../gems/devise-3.5.6/lib/devise/models/trackable.rb:23:in `update_tracked_fields'
[bundle].../gems/devise-3.5.6/lib/devise/models/trackable.rb:32:in `update_tracked_fields!'
[bundle].../gems/devise-3.5.6/lib/devise/hooks/trackable.rb:7:in `block in <top (required)>'
[bundle].../gems/warden-1.2.6/lib/warden/hooks.rb:14:in `call'
[bundle].../gems/warden-1.2.6/lib/warden/hooks.rb:14:in `block in _run_callbacks'
[bundle].../gems/warden-1.2.6/lib/warden/hooks.rb:9:in `each'
[bundle].../gems/warden-1.2.6/lib/warden/hooks.rb:9:in `_run_callbacks'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:51:in `_run_callbacks'
[bundle].../gems/warden-1.2.6/lib/warden/proxy.rb:179:in `set_user'
[bundle].../gems/devise-3.5.6/lib/devise/controllers/sign_in_out.rb:43:in `sign_in'
[bundle].../gems/devise-3.5.6/app/controllers/devise/registrations_controller.rb:106:in `sign_up'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/dc2faad7e93dfacf801d9110e989532b3fc32816/app/controllers/registrations_controller.rb#L18'>[app].../app/controllers/registrations_controller.rb:18:in `create'</a>
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:167:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:447:in `_run__137644518021050390__process_action__3669747562210056631__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:17:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
[bundle].../gems/activerecord-3.2.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:30:in `block in process_action'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:25:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:121:in `process'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:45:in `process'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:203:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:246:in `block in action'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:36:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/mapper.rb:43:in `call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:608:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/etag.rb:23:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/conditionalget.rb:35:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/head.rb:14:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/flash.rb:242:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
[bundle].../gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/cookies.rb:341:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/query_cache.rb:64:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `_run__2950446479684497095__call__1380203055803826778__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:32:in `call_app'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/tagged_logging.rb:22:in `tagged'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/request_id.rb:22:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/static.rb:63:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:140:in `forward'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:147:in `pass'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:159:in `invalidate'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:74:in `call!'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:51:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/engine.rb:484:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/application.rb:231:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/railtie/configurable.rb:30:in `method_missing'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/content_length.rb:14:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/log_tailer.rb:17:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/handler/webrick.rb:59:in `service'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/dc2faad7e93dfacf801d9110e989532b3fc32816/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L138'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/dc2faad7e93dfacf801d9110e989532b3fc32816/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L94'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/dc2faad7e93dfacf801d9110e989532b3fc32816/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb#L295'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'</a></pre>
Fingerprint: `ce471173bd65f97e5c08a4a293561e5c1acc5abe`

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>March 15, 2016 14:34:17 +0000</td></tr><tr><th>URL</th><td>[POST] http://zikaronbasalon.herokuapp.com/users.json</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td><table><tr><th>email</th><td>adinab21@gmail.com</td></tr><tr><th>password</th><td>[FILTERED]</td></tr><tr><th>password_confirmation</th><td>[FILTERED]</td></tr><tr><th>full_name</th><td>עדינה ברלין</td></tr><tr><th>type</th><td>host</td></tr></table></td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>registrations</td></tr><tr><th>format</th><td>json</td></tr><tr><th>registration</th><td><table><tr><th>user</th><td><table><tr><th>email</th><td>adinab21@gmail.com</td></tr><tr><th>password</th><td>[FILTERED]</td></tr><tr><th>password_confirmation</th><td>[FILTERED]</td></tr><tr><th>full_name</th><td>עדינה ברלין</td></tr><tr><th>type</th><td>host</td></tr></table></td></tr></table></td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>6451731ef37726aa10359c3f25af53a8</td></tr><tr><th>_csrf_token</th><td>qr9S0sxx/NB/qq9hppc4wcVkztc/nHDH1lren15X1WY=</td></tr><tr><th>warden.user.user.key</th><td>[[225], &quot;$2a$10$NzRlsegD7cEuqR.gFyesFe&quot;]</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/10.20.48.81&#39;&gt;10.20.48.81&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>application/json, text/plain, */*</td></tr></table></td></tr></table>
