### ISSUE TITLE
WitnessesController#show (ActionView::Template::Error) "undefined method `meta' for nil:NilClass"

### ISSUE THREAD

**Issue by uriklar** [uriklar/ZikaronBasalon#51]
<table><tr><th>Exception</th><td>undefined method `meta&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>March 28, 2016 16:46:39 +0000</td></tr><tr><th>Count</th><td>3</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/uriklar/ZikaronBasalon/blob/738b75751522e0ee31af59c77d77168f97625e5a/app/views/witnesses/show.html.erb#L48'>[app].../app/views/witnesses/show.html.erb:48:in `_app_views_witnesses_show_html_erb__4059833150786501186_70322478001220'</a>
[bundle].../gems/actionpack-3.2.14/lib/action_view/template.rb:145:in `block in render'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:125:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_view/template.rb:143:in `render'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/template_renderer.rb:48:in `block (2 levels) in render_template'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/template_renderer.rb:47:in `block in render_template'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/template_renderer.rb:55:in `render_with_layout'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/template_renderer.rb:46:in `render_template'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/template_renderer.rb:19:in `render'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:152:in `block in render_with_newrelic'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:151:in `render_with_newrelic'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/renderer.rb:36:in `render_template'
[bundle].../gems/actionpack-3.2.14/lib/action_view/renderer/renderer.rb:17:in `render'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:110:in `_render_template'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/streaming.rb:225:in `_render_template'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:103:in `render_to_body'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:88:in `render'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rendering.rb:16:in `render'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
[bundle].../gems/activesupport-3.2.14/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/738b75751522e0ee31af59c77d77168f97625e5a/vendor/ruby-2.0.0/lib/ruby/2.0.0/benchmark.rb#L296'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'</a>
[bundle].../gems/activesupport-3.2.14/lib/active_support/core_ext/benchmark.rb:5:in `ms'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
[bundle].../gems/activerecord-3.2.14/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:39:in `render'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/mime_responds.rb:196:in `respond_to'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/738b75751522e0ee31af59c77d77168f97625e5a/app/controllers/witnesses_controller.rb#L20'>[app].../app/controllers/witnesses_controller.rb:20:in `show'</a>
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:167:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:425:in `_run__306135995312964558__process_action__703198033308773414__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:17:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
[bundle].../gems/activerecord-3.2.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:30:in `block in process_action'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:25:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:121:in `process'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:45:in `process'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:203:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:246:in `block in action'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:36:in `call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:608:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/etag.rb:23:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/head.rb:14:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/flash.rb:242:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
[bundle].../gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/cookies.rb:341:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/query_cache.rb:64:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `_run__3292150064283182241__call__3687953586618966509__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:32:in `call_app'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/tagged_logging.rb:22:in `tagged'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/request_id.rb:22:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/static.rb:63:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:140:in `forward'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:249:in `fetch'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:189:in `lookup'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:66:in `call!'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:51:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/engine.rb:484:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/application.rb:231:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/railtie/configurable.rb:30:in `method_missing'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/content_length.rb:14:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/log_tailer.rb:17:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/handler/webrick.rb:59:in `service'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/738b75751522e0ee31af59c77d77168f97625e5a/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L138'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/738b75751522e0ee31af59c77d77168f97625e5a/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L94'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/738b75751522e0ee31af59c77d77168f97625e5a/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb#L295'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'</a></pre>
Fingerprint: `e581a28ca84e2a2cf95c1ab2a9add7961fffe0bb`

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>March 17, 2016 15:26:44 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/witnesses/136</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>witnesses</td></tr><tr><th>id</th><td>136</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/82.81.84.146&#39;&gt;82.81.84.146&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>March 17, 2016 15:26:56 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/witnesses/146</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>witnesses</td></tr><tr><th>id</th><td>146</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/82.81.84.146&#39;&gt;82.81.84.146&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>March 28, 2016 16:46:39 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/witnesses/396</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>witnesses</td></tr><tr><th>id</th><td>396</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/199.19.249.196&#39;&gt;199.19.249.196&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td></td></tr><tr><th>Accept</th><td>*/*</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>March 28, 2016 16:57:58 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/witnesses/438</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>witnesses</td></tr><tr><th>id</th><td>438</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/199.19.249.196&#39;&gt;199.19.249.196&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td></td></tr><tr><th>Accept</th><td>*/*</td></tr></table></td></tr></table>
