### ISSUE TITLE
ManagersController#show (NoMethodError) "undefined method `full_name' for nil:NilClass"

### ISSUE THREAD

**Issue by uriklar** [uriklar/ZikaronBasalon#54]
<table><tr><th>Exception</th><td>undefined method `full_name&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>March 17, 2016 21:42:08 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/uriklar/ZikaronBasalon/blob/10c8d12577fc938f3b6505719789c222ea1b3e65/app/models/manager.rb#L18'>[app].../app/models/manager.rb:18:in `block in get_hosts'</a>
[bundle].../gems/activerecord-3.2.14/lib/active_record/relation/query_methods.rb:72:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/relation/query_methods.rb:72:in `block in select'
[bundle].../gems/activerecord-3.2.14/lib/active_record/relation/query_methods.rb:72:in `select'
[bundle].../gems/activerecord-3.2.14/lib/active_record/relation/query_methods.rb:72:in `select'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/10c8d12577fc938f3b6505719789c222ea1b3e65/app/models/manager.rb#L18'>[app].../app/models/manager.rb:18:in `get_hosts'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/10c8d12577fc938f3b6505719789c222ea1b3e65/app/controllers/managers_controller.rb#L17'>[app].../app/controllers/managers_controller.rb:17:in `show'</a>
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:167:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:447:in `_run__2745565816178957169__process_action__1554143629478946488__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:17:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `block in instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
[bundle].../gems/activerecord-3.2.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:30:in `block in process_action'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:25:in `process_action'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/base.rb:121:in `process'
[bundle].../gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:45:in `process'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:203:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_controller/metal.rb:246:in `block in action'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:36:in `call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
[bundle].../gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:608:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/etag.rb:23:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/head.rb:14:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/flash.rb:242:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
[bundle].../gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/cookies.rb:341:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/query_cache.rb:64:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `_run__2365655603672035590__call__4557883486706815610__callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
[bundle].../gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:32:in `call_app'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `block in call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/tagged_logging.rb:22:in `tagged'
[bundle].../gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/request_id.rb:22:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/activesupport-3.2.14/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/actionpack-3.2.14/lib/action_dispatch/middleware/static.rb:63:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:140:in `forward'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:249:in `fetch'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:189:in `lookup'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:66:in `call!'
[bundle].../gems/rack-cache-1.6.1/lib/rack/cache/context.rb:51:in `call'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/engine.rb:484:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/application.rb:231:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/railtie/configurable.rb:30:in `method_missing'
[bundle].../gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/content_length.rb:14:in `call'
[bundle].../gems/railties-3.2.14/lib/rails/rack/log_tailer.rb:17:in `call'
[bundle].../gems/rack-1.4.7/lib/rack/handler/webrick.rb:59:in `service'
<a href='https://github.com/uriklar/ZikaronBasalon/blob/10c8d12577fc938f3b6505719789c222ea1b3e65/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L138'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/10c8d12577fc938f3b6505719789c222ea1b3e65/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb#L94'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'</a>
<a href='https://github.com/uriklar/ZikaronBasalon/blob/10c8d12577fc938f3b6505719789c222ea1b3e65/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb#L295'>[app].../vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'</a></pre>
Fingerprint: `05a9645499ef68c3118ba93d2e21c29475405ada`

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>March 17, 2016 21:42:08 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/managers/1.json?page=1&amp;host_query=%D7%A0&amp;sort=created_at</td></tr><tr><th>Params</th><td><table><tr><th>page</th><td>1</td></tr><tr><th>host_query</th><td>נ</td></tr><tr><th>sort</th><td>created_at</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>managers</td></tr><tr><th>id</th><td>1</td></tr><tr><th>format</th><td>json</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>4d73c86c92578e7a0649fd418567705a</td></tr><tr><th>warden.user.user.key</th><td>[[1], &quot;$2a$10$cK5NKoFZ0/6GYRoS8Xqj1O&quot;]</td></tr><tr><th>_csrf_token</th><td>vZ7zwHqsfBDeDlNaGYJIAq8zk8rjIekIM7dU5q1v1Y0=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/5.22.135.193&#39;&gt;5.22.135.193&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>application/json, text/plain, */*</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>March 17, 2016 21:42:10 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/managers/1.json?page=1&amp;host_query=%D7%A0%D7%95%D7%A2%D7%94&amp;sort=created_at</td></tr><tr><th>Params</th><td><table><tr><th>page</th><td>1</td></tr><tr><th>host_query</th><td>נועה</td></tr><tr><th>sort</th><td>created_at</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>managers</td></tr><tr><th>id</th><td>1</td></tr><tr><th>format</th><td>json</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>4d73c86c92578e7a0649fd418567705a</td></tr><tr><th>warden.user.user.key</th><td>[[1], &quot;$2a$10$cK5NKoFZ0/6GYRoS8Xqj1O&quot;]</td></tr><tr><th>_csrf_token</th><td>vZ7zwHqsfBDeDlNaGYJIAq8zk8rjIekIM7dU5q1v1Y0=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/5.22.135.193&#39;&gt;5.22.135.193&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>application/json, text/plain, */*</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>March 17, 2016 21:42:25 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/managers/1.json?page=1&amp;host_query=%D7%A0%D7%95%D7%A2%D7%94&amp;sort=created_at</td></tr><tr><th>Params</th><td><table><tr><th>page</th><td>1</td></tr><tr><th>host_query</th><td>נועה</td></tr><tr><th>sort</th><td>created_at</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>managers</td></tr><tr><th>id</th><td>1</td></tr><tr><th>format</th><td>json</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>4d73c86c92578e7a0649fd418567705a</td></tr><tr><th>warden.user.user.key</th><td>[[1], &quot;$2a$10$cK5NKoFZ0/6GYRoS8Xqj1O&quot;]</td></tr><tr><th>_csrf_token</th><td>vZ7zwHqsfBDeDlNaGYJIAq8zk8rjIekIM7dU5q1v1Y0=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/5.22.135.193&#39;&gt;5.22.135.193&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by uriklar** [comment]
<table><tr><th>Occurred At</th><td>March 17, 2016 21:42:48 +0000</td></tr><tr><th>URL</th><td>[GET] http://zikaronbasalon.herokuapp.com/managers/1.json?page=1&amp;host_query=%D7%A0%D7%95%D7%A2&amp;sort=created_at</td></tr><tr><th>Params</th><td><table><tr><th>page</th><td>1</td></tr><tr><th>host_query</th><td>נוע</td></tr><tr><th>sort</th><td>created_at</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>managers</td></tr><tr><th>id</th><td>1</td></tr><tr><th>format</th><td>json</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>4d73c86c92578e7a0649fd418567705a</td></tr><tr><th>warden.user.user.key</th><td>[[1], &quot;$2a$10$cK5NKoFZ0/6GYRoS8Xqj1O&quot;]</td></tr><tr><th>_csrf_token</th><td>vZ7zwHqsfBDeDlNaGYJIAq8zk8rjIekIM7dU5q1v1Y0=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/5.22.135.193&#39;&gt;5.22.135.193&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>application/json, text/plain, */*</td></tr></table></td></tr></table>
